FROM node:20.12.0-alpine

WORKDIR /usr/app

COPY ./cms-composer/package.json .
COPY ./cms-sdk ./cms-sdk
RUN npm install --only=production && npm install --only=dev

COPY ./cms-composer .

EXPOSE 7781

# Healthcheck to ensure the service is responding
HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD wget -qO- http://localhost:7781/health > /dev/null 2>&1 || exit 1

CMD ["npm", "run", "start:dev"]
